### PR TITLE
DEV-9254 Add support for Laravel 6

### PR DESCRIPTION
**Pull request by dbhynds**

### CODE REVIEW

**Comment by vkoves** [comment]
@dbhynds - is this PR complete as is?

**Comment by dbhynds** [comment]
Yep. I just needed to add support for laravel 6 so we could upgrade the App API

**Comment by dbhynds** [comment]
Sorry, was about to fill out the description, but you beat me to it.

**Review by vkoves — APPROVED** [review]
Looks good to me - I didn't test this but I feel very confident in the change :laughing:

**Pull request merged**
